# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Alexander (Sasha) Pastukhov
email: pastukhov.alexander@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Akademischer Rat @ Department of General Psychology and Methodoly, University of Bamberg
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://alexander-pastukhov.github.io" # the base hostname & protocol for your site

# Social media profiles - feel free to add more here
#twitter_username: SBootstrap
github_username:  alexander-pastukhov
#facebook_username: StartBootstrap
#instagram_username: beyonce
#stackoverflow_url: https://
#googleplus_username: BobMarley
#skype_username: echo123
linkedin_url: https://www.linkedin.com/in/alexander-sasha-pastukhov-3722b05/

# Address information
address_street: 3034 Melrose Place
address_city: Beverly Hills
address_state: CA
address_zip: 90201

# Build settings
markdown: kramdown

collections:
- publications